version: '3.8'

services:
  tts-service:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ./voice_cloning_recordings:/app/voice_cloning_recordings
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped