[project]
name = "voiceclone"
version = "0.1.0"
description = "VoiceClone - Unlimited Chatterbox"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio>=5.32.1",
    "numpy>=2.2.6",
    "torch>=2.7.0",
]
